[package]
name = "visualizer_zcash"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.30.12"
softbuffer = "0.4.6"
num_cpus = "1.17.0"
twox-hash = "2.1.2"
rand = "0.9.2"
rustybuzz = "0.20.1"
swash = "0.2.6"
rodio = "0.21.1"
arboard = "3.6.1"

[profile.release]
debug = true
